### ISSUE TITLE
Install Done. But Not completely effective

### ISSUE THREAD

**Issue by lan9635** [Midocean-Technologies/business_theme_v14#1]
Just Like This: No Pagination effect
![image](https://user-images.githubusercontent.com/84449561/197094073-5f20067d-7a4c-4eb2-b51d-be4c1b8e8036.png)

I Will Like this :
![image](https://user-images.githubusercontent.com/84449561/197094273-892067b3-75a0-41f7-9b4a-cf9c5c73cb5e.png)

**Comment by sagar-bhogayata** [comment]
Which frappe version do you have? @lan9635 
Tabbed view added in frappe v14
