### ISSUE TITLE
Website Theme Edit not Applied!

### ISSUE THREAD

**Issue by mohsen-zanjani** [Midocean-Technologies/business_theme_v14#10]
Hi, After installing the theme, the changes applied in the section  `Website > Website Theme > Standard` are not applied!

![Standard](https://github.com/Midocean-Technologies/business_theme_v14/assets/31995071/48330fce-eb95-491d-af04-8928abaf5eb9)

**Comment by ibashirbwn** [comment]
not showing in toggle theme

**Comment by sagar-bhogayata** [comment]
This might lead to CSS conflicts with existing styles.
