### ISSUE TITLE
Wrong calculated position of floating form-tabs

### ISSUE THREAD

**Issue by kolewu** [Midocean-Technologies/business_theme_v14#6]
After scrolling the position of the form-tabs are wrong:

![After loading the page](https://github.com/Midocean-Technologies/business_theme_v14/assets/95135/85d39d94-f75e-4f6f-acb7-10bedadae7fb)

![After scrolling down and up again (to get to the same position)](https://github.com/Midocean-Technologies/business_theme_v14/assets/95135/78c5a256-973d-43cf-936a-e51e865a5e02)

The css variables `--page-head-height` and `--navbar-height` are used to calculate the position of the form-tabs when scrolling. Since the variable values are defined in the [frappe main theme](https://github.com/frappe/frappe/blob/develop/frappe/public/scss/desk/css_variables.scss#L29) but the theme uses different values without changing the variables, the position of the the form-tabs is calculated with a wrong size and because this size is too big, it covers part of the form.

**Comment by sagar-bhogayata** [comment]
@kolewu It's merged, Thanks
